def query_base_consulta():
    query = """
    SELECT
        V.EMPRESA,
        V.REVENDA_ORIGEM AS REVENDA,
        (SELECT NOME_FANTASIA FROM GER_REVENDA WHERE EMPRESA = V.EMPRESA AND REVENDA = V.REVENDA_ORIGEM) AS NOME_FANTASIA,
        V.VEICULO AS COD_VEICULO,
        V.CHASSI,
        M.MODELO,
        M.DES_MODELO,
        F.PLACA,
        F.ANO_FABRICACAO,
        F.ANO_MODELO,
        V.SITUACAO,
        V.QUILOMETRAGEM,
        V.NOVO_USADO, -- <--- IMPORTANTE: ADICIONADA PARA O DASHBOARD IDENTIFICAR!
        
        -- [[[ COLOQUE AQUI OS SEUS BLOCOS DE COALESCE(CUSTO) E CASE(PREÇO E STATUS) ]]] --
        
        V.DTA_ENTRADA_ESTOQUE
    FROM VEI_VEICULO V
    INNER JOIN VEI_MODELO M ON (V.EMPRESA = M.EMPRESA AND V.MODELO = M.MODELO)
    INNER JOIN OFI_FICHA_SEGUIMENTO F ON (V.CHASSI = F.CHASSI)
    INNER JOIN VEI_FAMILIA FA ON (FA.EMPRESA = M.EMPRESA AND FA.FAMILIA = M.FAMILIA)
    LEFT OUTER JOIN VEI_MODELO_PRECO P ON (V.EMPRESA = P.EMPRESA AND V.MODELO = P.MODELO AND V.REVENDA_ORIGEM = P.REVENDA)
    WHERE V.EMPRESA = 1
    AND V.REVENDA_ORIGEM IN (1, 2, 3, 4)
    AND V.SITUACAO = 'ES'
    """
    return query